# Generated by Django 6.0.5 on 2026-05-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_autors_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False),
        ),
    ]
