# Generated by Django 6.0.5 on 2026-05-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_autor_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
