# Generated by Django 6.0.5 on 2026-05-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_posts_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='autors',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
