# Generated by Django 6.0.5 on 2026-05-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_autors_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='autors',
            name='adreça',
            field=models.EmailField(max_length=254),
        ),
    ]
