# Generated by Django 6.0.5 on 2026-05-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_tag_slug_alter_autors_adreça'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autors',
            name='cognom',
            field=models.TextField(max_length=15),
        ),
        migrations.AlterField(
            model_name='autors',
            name='nom',
            field=models.TextField(max_length=15),
        ),
        migrations.AlterField(
            model_name='tag',
            name='nom_tag',
            field=models.TextField(max_length=20),
        ),
    ]
