# Generated by Django 6.0.5 on 2026-05-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_autors_cognom_alter_autors_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='nom_tag',
            field=models.CharField(max_length=20),
        ),
    ]
